language: csharp
mono: none
dotnet: 2.1.502
dist: trusty
    
branches:
  only:
    - master
    
jobs:
  include:
    - stage: post_message
      script:
        - cd PostMessage/src/PostMessage
        - dotnet build