language: csharp
mono: none
dotnet: 2.2.104
dist: trusty
sudo: false
    
branches:
  only:
    - master
    
before_install:
  - dotnet restore

jobs:
  include:
    - stage: post_message
      script:
        - cd PostMessage/src/PostMessage
        - dotnet build