AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Do everything

Parameters:
  UserPoolName:
    Type: String
    Description: The name of the cognito user pool
  
Resources:
  #################
  ### User Pool ###
  #################
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
#      MfaConfiguration: OFF
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
      AliasAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ChatClient
      GenerateSecret: false
      UserPoolId: !Ref UserPool
  